---
include:
  - project: 'kits-maxiv/cfg-maxiv-gitlabci'
    file: PreCommit.gitlab-ci.yml

stages:
  - check
  - test

run-pre-commit:
  allow_failure: true

run-test:
  stage: test
  image: mambaorg/micromamba:latest
  tags:
    - kubernetes
  parallel:
    matrix:
      - PYTHON_VER: ["3.8", "3.9", "3.10"]
  coverage: '/^TOTAL.+?(\d+\%)$/'
  before_script:
    # There is no wheel for python-ldap which depends on openldap
    # We install it with conda
    - eval "$(/bin/micromamba shell hook -s bash)"
    - >
      micromamba install -y -n base -c conda-forge
      python=$PYTHON_VER pip python-ldap=3.4.0
    - micromamba activate base
    # note: install 'tango' packages as well, as they are required to run unit tests
    - python -m pip install -e '.[tango]' pytest pytest-cov pytest-mock
  script:
    - pytest -v --cov-report term-missing --cov-report html --junitxml=report.xml
  artifacts:
    when: always
    paths:
      - htmlcov/
      - report.xml
    reports:
      junit: report.xml
