---


# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details


# This uses custom commands, because we need to install dependencies
# from both Conda and Poetry.


version: 2

build:

  os: "ubuntu-22.04"

  tools:
    python: "mambaforge-22.9"

  commands:
    - "mamba env create --file conda-environment-dev.yml"
    - "mamba run --name mxcubecore poetry install --only=docs,main"
    - "mamba run --name mxcubecore poetry run sphinx-build -T -E -b html -c ./docs/ ./docs/source/ ${READTHEDOCS_OUTPUT}/html/"

# `conda.environment` is probably not used, since we use custom commands only,
# but it seems to be required (wrongly) by ReadTheDocs config file validation.
# https://github.com/readthedocs/readthedocs.org/pull/10979#issuecomment-1896036953
conda:
  environment: "conda-environment-dev.yml"


...  # EOF
